name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: lint src with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          version: "~= 22.0"
      - name: lint tests with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./tests"
          version: "~= 22.0"
      - name: lint notebooks with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./notebooks"
          jupyter: true
          version: "~= 22.0"
      - name: check src typehints if present
        run: mypy src 
      - name: check tests typehints if present
        run: mypy tests
      - name: pylint on the source
        run: pylint src
      - name: Test with pytest
        run: |
          pytest
      - name: Build package
        run: python -m build